services:
  # Backend API service
  - type: web
    name: askmydoc-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false
    autoDeploy: true

  # Frontend Next.js application
  - type: web
    name: askmydoc-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://askmydoc-backend-lr1q.onrender.com
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: NODE_ENV
        value: production
    autoDeploy: true